/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import dao.ProductDAO;
import java.util.ArrayList;
import java.util.List;
import models.OrderItem;
import models.Product;
import models.User;

/**
 *
 * @author Anis
 */
public class HomeFrame extends javax.swing.JFrame {

    private final User currentUser;
    private final List<OrderItem> cart = new ArrayList<>();
    private final ProductDAO productDAO = new ProductDAO();
    private javax.swing.table.DefaultTableModel tableModel;

    public HomeFrame(User user) {
        if (user == null) {
            initComponents();
            javax.swing.JOptionPane.showMessageDialog(null,
                    "Accès refusé. Veuillez vous connecter d'abord.", "Non autorisé",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            dispose();
            new Loginframe().setVisible(true);
            return;
        }
        this.currentUser = user;
        initComponents();
        lblWelcome.setText("Bonjour, " + (user != null ? user.getFullName() : "Invité"));
        setupTable();
        getContentPane().setBackground(new java.awt.Color(44, 62, 80));
        setLocationRelativeTo(null);
        loadProducts(productDAO.getAllProducts());
    }

    private void setupTable() {
        tableModel = new javax.swing.table.DefaultTableModel(
                new String[]{"ID", "Nom du Produit", "Catégorie", "Prix", "En Stock", "Description"}, 0) {
            public boolean isCellEditable(int r, int c) {
                return false;
            }
        };
        jTable1.setModel(tableModel);
        jTable1.getTableHeader().setFont(new java.awt.Font("Segoe UI", 1, 13));
        jTable1.getTableHeader().setBackground(new java.awt.Color(44, 62, 80));
        jTable1.getTableHeader().setForeground(new java.awt.Color(96, 96, 96));
        jTable1.setRowHeight(30);
        jTable1.setGridColor(new java.awt.Color(236, 240, 241));
        jTable1.setSelectionBackground(new java.awt.Color(214, 234, 248));
        jTable1.setSelectionForeground(java.awt.Color.BLACK);
        int[] widths = {40, 210, 100, 80, 80, 250};
        for (int i = 0; i < widths.length; i++) {
            jTable1.getColumnModel().getColumn(i).setPreferredWidth(widths[i]);
        }
    }

    private void loadProducts(List<Product> products) {
        tableModel.setRowCount(0);
        for (Product p : products) {
            tableModel.addRow(new Object[]{
                p.getId(), p.getName(), p.getCategory(),
                String.format(java.util.Locale.US, "TND%.2f", p.getPrice()), p.getStock(), p.getDescription()
            });
        }
    }

    private void updateCartBtn() {
        int total = cart.stream().mapToInt(OrderItem::getQuantity).sum();
        btnCart.setText("🛒 Panier (" + total + ")");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogo = new javax.swing.JLabel();
        lblWelcome = new javax.swing.JLabel();
        btnCart = new javax.swing.JButton();
        btnOrders = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        lblSearch = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        lblCategory = new javax.swing.JLabel();
        cmbCategory = new javax.swing.JComboBox<>();
        btnFilter = new javax.swing.JButton();
        btnAddToCart = new javax.swing.JButton();
        productTable = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(44, 62, 80));
        setPreferredSize(new java.awt.Dimension(900, 620));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogo.setFont(new java.awt.Font("Georgia", 1, 20)); // NOI18N
        lblLogo.setForeground(new java.awt.Color(255, 255, 255));
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/stack-of-books.png"))); // NOI18N
        lblLogo.setText("Smart Info");
        lblLogo.setPreferredSize(new java.awt.Dimension(220, 30));
        getContentPane().add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 15, -1, -1));

        lblWelcome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(255, 255, 255));
        lblWelcome.setText("Bonjour, Invité");
        lblWelcome.setPreferredSize(new java.awt.Dimension(120, 30));
        getContentPane().add(lblWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 100, -1));

        btnCart.setBackground(new java.awt.Color(61, 81, 102));
        btnCart.setForeground(new java.awt.Color(255, 255, 255));
        btnCart.setText("🛒 Panier (0)");
        btnCart.setBorderPainted(false);
        btnCart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCart.setFocusPainted(false);
        btnCart.setPreferredSize(new java.awt.Dimension(110, 35));
        btnCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCartActionPerformed(evt);
            }
        });
        getContentPane().add(btnCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, -1, -1));

        btnOrders.setBackground(new java.awt.Color(61, 81, 102));
        btnOrders.setForeground(new java.awt.Color(255, 255, 255));
        btnOrders.setText("📋 Mes Commandes");
        btnOrders.setBorderPainted(false);
        btnOrders.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOrders.setFocusPainted(false);
        btnOrders.setPreferredSize(new java.awt.Dimension(110, 35));
        btnOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdersActionPerformed(evt);
            }
        });
        getContentPane().add(btnOrders, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 150, -1));

        btnLogout.setBackground(new java.awt.Color(255, 51, 51));
        btnLogout.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Deconnecter");
        btnLogout.setBorderPainted(false);
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.setFocusPainted(false);
        btnLogout.setPreferredSize(new java.awt.Dimension(80, 35));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, 110, -1));

        lblSearch.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSearch.setForeground(new java.awt.Color(255, 255, 255));
        lblSearch.setText("Recherche:");
        lblSearch.setPreferredSize(new java.awt.Dimension(60, 30));
        getContentPane().add(lblSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 65, 70, -1));

        txtSearch.setPreferredSize(new java.awt.Dimension(200, 30));
        getContentPane().add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 65, -1, -1));

        btnSearch.setBackground(new java.awt.Color(52, 152, 219));
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("🔍 Chercher");
        btnSearch.setBorderPainted(false);
        btnSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearch.setFocusPainted(false);
        btnSearch.setPreferredSize(new java.awt.Dimension(100, 30));
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 65, -1, -1));

        lblCategory.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCategory.setForeground(new java.awt.Color(255, 255, 255));
        lblCategory.setText("Catégorie");
        lblCategory.setPreferredSize(new java.awt.Dimension(75, 30));
        getContentPane().add(lblCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 65, -1, -1));

        cmbCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Toutes les catégories", "Livre", "Cahier", "Stylo", "Papeterie", "Autre" }));
        cmbCategory.setPreferredSize(new java.awt.Dimension(150, 30));
        getContentPane().add(cmbCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 65, -1, -1));

        btnFilter.setBackground(new java.awt.Color(142, 68, 173));
        btnFilter.setForeground(new java.awt.Color(255, 255, 255));
        btnFilter.setText("Filtrer");
        btnFilter.setBorderPainted(false);
        btnFilter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFilter.setFocusPainted(false);
        btnFilter.setPreferredSize(new java.awt.Dimension(80, 30));
        btnFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilterActionPerformed(evt);
            }
        });
        getContentPane().add(btnFilter, new org.netbeans.lib.awtextra.AbsoluteConstraints(615, 65, -1, -1));

        btnAddToCart.setBackground(new java.awt.Color(39, 174, 96));
        btnAddToCart.setForeground(new java.awt.Color(255, 255, 255));
        btnAddToCart.setText("➕ Ajouter au panier");
        btnAddToCart.setBorderPainted(false);
        btnAddToCart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddToCart.setFocusPainted(false);
        btnAddToCart.setPreferredSize(new java.awt.Dimension(140, 30));
        btnAddToCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddToCartActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddToCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 65, -1, -1));

        productTable.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        productTable.setPreferredSize(new java.awt.Dimension(875, 450));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        productTable.setViewportView(jTable1);

        getContentPane().add(productTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        lblStatus.setFont(new java.awt.Font("Segoe UI", 2, 11)); // NOI18N
        lblStatus.setForeground(new java.awt.Color(189, 195, 199));
        lblStatus.setText("Sélectionnez un produit et cliquez sur Ajouter au panier");
        lblStatus.setPreferredSize(new java.awt.Dimension(875, 25));
        getContentPane().add(lblStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 575, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        dispose();
        new Loginframe().setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String kw = txtSearch.getText().trim();
        if (kw.isEmpty())
            loadProducts(productDAO.getAllProducts());
        else
            loadProducts(productDAO.searchProducts(kw));
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilterActionPerformed
        String cat = (String) cmbCategory.getSelectedItem();
        if ("Tous les Catégories".equals(cat))
            loadProducts(productDAO.getAllProducts());
        else
            loadProducts(productDAO.getByCategory(cat));
    }//GEN-LAST:event_btnFilterActionPerformed

    private void btnAddToCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddToCartActionPerformed
        int row = jTable1.getSelectedRow();
        if (row == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Veuillez sélectionner un produit.");
            return;
        }
        int productId = (int) tableModel.getValueAt(row, 0);
        String name = (String) tableModel.getValueAt(row, 1);
        int stock = (int) tableModel.getValueAt(row, 4);
        double price = Double.parseDouble(
                tableModel.getValueAt(row, 3).toString()
                        .replace("TND", "")
                        .replace(",", "."));
        String category = (String) tableModel.getValueAt(row, 2);
        if (stock == 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Rupture de stock.");
            return;
        }
        String qtyStr = javax.swing.JOptionPane.showInputDialog(this, "Quantité (max " + stock + "):", "1");
        if (qtyStr == null) {
            return;
        }
        int qty;
        try {
            qty = Integer.parseInt(qtyStr.trim());
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Quantité invalide.");
            return;
        }
        if (qty < 1 || qty > stock) {
            javax.swing.JOptionPane.showMessageDialog(this, "Saisissez un nombre entre 1 et " + stock + ".");
            return;
        }
        Product product = new Product(productId, name, "", price, stock, category);
        for (OrderItem item : cart) {
            if (item.getProduct().getId() == productId) {
                item.setQuantity(item.getQuantity() + qty);
                updateCartBtn();
                javax.swing.JOptionPane.showMessageDialog(this, "Panier mis à jour ✓");
                return;
            }
        }
        cart.add(new OrderItem(product, qty));
        updateCartBtn();
        javax.swing.JOptionPane.showMessageDialog(this, "\"" + name + "\" Ajouté au panier ✓");
    }//GEN-LAST:event_btnAddToCartActionPerformed

    private void btnCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCartActionPerformed
        new CartFrame(currentUser, cart).setVisible(true);
    }//GEN-LAST:event_btnCartActionPerformed

    private void btnOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdersActionPerformed
        new OrderHistoryFrame(currentUser).setVisible(true);
    }//GEN-LAST:event_btnOrdersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeFrame(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddToCart;
    private javax.swing.JButton btnCart;
    private javax.swing.JButton btnFilter;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnOrders;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cmbCategory;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JScrollPane productTable;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
