/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import dao.OrderDAO;
import models.User;

/**
 *
 * @author Anis
 */
public class OrderHistoryFrame extends javax.swing.JFrame {

    /**
     * Creates new form OrderHistoryFrame
     */
    private final User currentUser;
    private javax.swing.table.DefaultTableModel tableModel;

    public OrderHistoryFrame(User user) {
        this.currentUser = user;
        initComponents();
        setupTable();
        orderTable.setRowHeight(32);
        getContentPane().setBackground(new java.awt.Color(44, 62, 80));

        orderTable.getTableHeader().setFont(new java.awt.Font("Segoe UI", 1, 13));
        orderTable.getTableHeader().setBackground(new java.awt.Color(44, 62, 80));
        orderTable.getTableHeader().setForeground(new java.awt.Color(96, 96, 96));
        orderTable.setRowHeight(30);
        orderTable.setGridColor(new java.awt.Color(236, 240, 241));
        orderTable.setSelectionBackground(new java.awt.Color(214, 234, 248));
        orderTable.setSelectionForeground(java.awt.Color.BLACK);
        lblTitle.setText("📋  My Order History — "
                + (user != null ? user.getFullName() : ""));
        setLocationRelativeTo(null);
        loadOrders();
    }

    private void setupTable() {
        tableModel = new javax.swing.table.DefaultTableModel(
                new String[]{"Order ID", "Total", "Status", "Date"}, 0) {
            public boolean isCellEditable(int r, int c) {
                return false;
            }
        };
        orderTable.setModel(tableModel);
        int[] widths = {90, 110, 120, 220};
        for (int i = 0; i < widths.length; i++) {
            orderTable.getColumnModel().getColumn(i).setPreferredWidth(widths[i]);
        }

        // Color rows by status
        orderTable.setDefaultRenderer(Object.class,
                new javax.swing.table.DefaultTableCellRenderer() {
            @Override
            public java.awt.Component getTableCellRendererComponent(
                    javax.swing.JTable t, Object v, boolean sel,
                    boolean foc, int r, int c) {
                java.awt.Component comp
                        = super.getTableCellRendererComponent(t, v, sel, foc, r, c);
                if (!sel && tableModel.getRowCount() > r) {
                    String status = tableModel.getValueAt(r, 2).toString();
                    switch (status) {
                        case "confirmed":
                            comp.setBackground(new java.awt.Color(213, 245, 227));
                            break;
                        case "pending":
                            comp.setBackground(new java.awt.Color(254, 249, 231));
                            break;
                        case "cancelled":
                            comp.setBackground(new java.awt.Color(250, 220, 220));
                            break;
                        default:
                            comp.setBackground(java.awt.Color.WHITE);
                            break;
                    }
                }
                return comp;
            }
        });
    }

    private void loadOrders() {
        tableModel.setRowCount(0);
        OrderDAO dao = new OrderDAO();
        java.util.List<String[]> orders = dao.getOrderHistory(currentUser.getId());
        if (orders.isEmpty()) {
            tableModel.addRow(new String[]{"—", "—", "No orders yet", "—"});
        } else {
            for (String[] row : orders) {
                tableModel.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        scrollPane = new javax.swing.JScrollPane();
        orderTable = new javax.swing.JTable();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Library Store — My Orders");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setBackground(new java.awt.Color(142, 68, 173));
        lblTitle.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("📋  My Order History");
        lblTitle.setPreferredSize(new java.awt.Dimension(680, 50));
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        scrollPane.setPreferredSize(new java.awt.Dimension(660, 300));

        orderTable.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        orderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollPane.setViewportView(orderTable);

        getContentPane().add(scrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        btnClose.setBackground(new java.awt.Color(142, 68, 173));
        btnClose.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnClose.setForeground(new java.awt.Color(255, 255, 255));
        btnClose.setText("Close");
        btnClose.setBorderPainted(false);
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.setFocusPainted(false);
        btnClose.setPreferredSize(new java.awt.Dimension(110, 35));
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 375, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderHistoryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderHistoryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderHistoryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderHistoryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderHistoryFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable orderTable;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables
}
