/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import dao.UserDAO;

/**
 *
 * @author Anis
 */
public class RegisterFrame extends javax.swing.JFrame {

    /**
     * Creates new form RegisterFrame
     */
    private final StringBuilder realPassword = new StringBuilder();
    private final StringBuilder realConfirm = new StringBuilder();

    public RegisterFrame() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(44, 62, 80));
        setupPasswordMasking(txtPassword, realPassword);
        setupPasswordMasking(txtConfirm, realConfirm);
        setLocationRelativeTo(null);
    }

    /**
     * Makes a plain JTextField behave like a password field (shows bullets,
     * stores real text).
     */
    private void setupPasswordMasking(javax.swing.JTextField field, StringBuilder realText) {
        field.setDocument(new javax.swing.text.PlainDocument() {
            @Override
            public void insertString(int offs, String str, javax.swing.text.AttributeSet a)
                    throws javax.swing.text.BadLocationException {
                if (str == null) {
                    return;
                }
                realText.insert(offs, str);
                String bullets = str.replaceAll(".", "•");
                super.insertString(offs, bullets, a);
            }

            @Override
            public void remove(int offs, int len) throws javax.swing.text.BadLocationException {
                realText.delete(offs, offs + len);
                super.remove(offs, len);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblFullName = new javax.swing.JLabel();
        txtFullName = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        lblConfirm = new javax.swing.JLabel();
        txtConfirm = new javax.swing.JTextField();
        lblStatus = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Library Store — Register");
        setBackground(new java.awt.Color(26, 188, 156));
        setPreferredSize(new java.awt.Dimension(450, 580));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText(" + Create Your Account");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 25, -1, -1));

        lblFullName.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblFullName.setForeground(new java.awt.Color(255, 255, 255));
        lblFullName.setText("Full Name");
        getContentPane().add(lblFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 90, -1, -1));

        txtFullName.setPreferredSize(new java.awt.Dimension(300, 36));
        txtFullName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFullNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 110, -1, -1));

        lblEmail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setText("Email Address");
        getContentPane().add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 155, -1, -1));

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtEmail.setMinimumSize(new java.awt.Dimension(300, 34));
        txtEmail.setPreferredSize(new java.awt.Dimension(300, 34));
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 175, -1, -1));

        lblUsername.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setText("Username");
        getContentPane().add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 220, -1, -1));

        txtUsername.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtUsername.setPreferredSize(new java.awt.Dimension(300, 34));
        getContentPane().add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 240, -1, -1));

        lblPassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword.setText("Password");
        getContentPane().add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 285, -1, -1));

        txtPassword.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtPassword.setPreferredSize(new java.awt.Dimension(300, 34));
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 305, -1, -1));

        lblConfirm.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblConfirm.setForeground(new java.awt.Color(255, 255, 255));
        lblConfirm.setText("Confirm Password");
        getContentPane().add(lblConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 350, -1, -1));

        txtConfirm.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtConfirm.setPreferredSize(new java.awt.Dimension(300, 34));
        txtConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConfirmActionPerformed(evt);
            }
        });
        getContentPane().add(txtConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 370, -1, -1));

        lblStatus.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblStatus.setForeground(new java.awt.Color(255, 51, 51));
        lblStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStatus.setText(" ");
        lblStatus.setPreferredSize(new java.awt.Dimension(300, 20));
        getContentPane().add(lblStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 415, -1, -1));

        btnRegister.setBackground(new java.awt.Color(26, 188, 156));
        btnRegister.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(153, 153, 153));
        btnRegister.setText("CREATE ACCOUNT");
        btnRegister.setBorderPainted(false);
        btnRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegister.setFocusPainted(false);
        btnRegister.setPreferredSize(new java.awt.Dimension(300, 40));
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 445, -1, -1));

        btnBack.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btnBack.setForeground(new java.awt.Color(22, 160, 133));
        btnBack.setText("Already have an account? Login");
        btnBack.setBorderPainted(false);
        btnBack.setContentAreaFilled(false);
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.setPreferredSize(new java.awt.Dimension(300, 30));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 495, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        String fullName = txtFullName.getText().trim();
        String email = txtEmail.getText().trim();
        String username = txtUsername.getText().trim();
        String password = realPassword.toString();
        String confirm = realConfirm.toString();

        if (fullName.isEmpty() || email.isEmpty() || username.isEmpty() || password.isEmpty()) {
            showStatus("All fields are required.", java.awt.Color.RED);
            return;
        }
        if (password.length() < 6) {
            showStatus("Password must be at least 6 characters.", java.awt.Color.RED);
            return;
        }
        if (!password.equals(confirm)) {
            showStatus("Passwords do not match.", java.awt.Color.RED);
            return;
        }
        if (!email.contains("@") || !email.contains(".")) {
            showStatus("Enter a valid email address.", java.awt.Color.RED);
            return;
        }
        UserDAO dao = new UserDAO();
        if (dao.usernameExists(username)) {
            showStatus("Username already taken.", java.awt.Color.RED);
            return;
        }
        if (dao.register(username, password, email, fullName)) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Account created! You can now log in.", "Success",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
            dispose();
            new Loginframe().setVisible(true);
        } else {
            showStatus("Registration failed. Email may already exist.", java.awt.Color.RED);
        }
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        dispose();
        new Loginframe().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void showStatus(String msg, java.awt.Color color) {
        lblStatus.setText(msg);
        lblStatus.setForeground(color);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel lblConfirm;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFullName;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTextField txtConfirm;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
